# Generated by Django 3.0.1 on 2020-01-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('bookingDate', models.DateField(auto_now_add=True)),
                ('functionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('joiningdate', models.DateField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('specification', models.CharField(max_length=50)),
            ],
        ),
    ]
